from typing import Annotated, List, Dict, Optional, TypedDict
from operator import add
from app.core.schemas import FactSheet, AgentLogEntry

class CampaignState(TypedDict):
    """
    The Shared State for the Autonomous Content Factory Graph.
    This dictates what data each 'node' (agent) can see and modify.
    """
    
    # 1. Inputs
    campaign_id: str
    source_text: str
    
    # 2. Key Artifact: The Fact-Sheet
    # Modified only by the Lead Researcher
    fact_sheet: Optional[FactSheet]
    
    # 3. Output Drafts (Blog, Email, Social)
    # Generated by Copywriter, Validated by Editor
    drafts: Dict[str, str]
    
    # 4. Review Metadata
    # Used for the Feedback Loop (Editor -> Copywriter)
    correction_notes: Optional[str]
    is_approved: bool
    loop_count: int
    
    # 5. The Real-time Log Stream (Reducer)
    # Annotated[..., add] allows multiple nodes to append logs without overwriting
    logs: Annotated[List[AgentLogEntry], add]
