from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

class AgentLogEntry(BaseModel):
    """
    Schema for individual real-time logs sent from an AI Agent to the UI.
    Matches the 'Live Chat Feed' requirements.
    """
    agent_id: str = Field(..., description="E.g., researcher, copywriter, editor")
    agent_name: str = Field(..., description="Human-friendly name for display")
    message: str = Field(..., description="The message or 'thought' from the agent")
    status: str = Field("thinking", description="thinking | typing | completed | error")
    timestamp: datetime = Field(default_factory=datetime.utcnow)

class FactItem(BaseModel):
    """A single verified piece of information with its origin."""
    fact: str
    source_quote: Optional[str] = Field(None, description="The exact sentence from the source that proves this fact.")
    category: Optional[str] = None

class FactSheet(BaseModel):
    """
    The 'Source of Truth' generated by the Lead Research Agent.
    All other agents rely on this for grounding.
    """
    campaign_id: str
    
    # The Core Data
    value_proposition: str = Field(..., description="The 'Elevator Pitch' extracted from the source.")
    core_product_features: List[FactItem]
    technical_specs: Optional[List[FactItem]] = Field(default_factory=list, description="Optional. Technical specs if found in the document.")
    target_audience: Optional[List[str]] = Field(default_factory=list, description="Optional. Target audience segments if found in the document.")
    
    # Brand & Tone Context
    brand_voice_directives: List[str] = Field(
        default_factory=list, 
        description="Implicit or explicit tone instructions found in the document (e.g., 'Avoid jargon')."
    )
    
    # The 'Red Flags' for the Editor
    ambiguous_statements: List[str] = Field(
        default_factory=list, 
        description="Claims that couldn't be verified or seem like 'marketing fluff' without data."
    )
    
    created_at: datetime = Field(default_factory=datetime.utcnow)

class EmailDraft(BaseModel):
    subject: str = Field(..., description="Short, punchy B2B outreach subject line.")
    body: str = Field(..., description="Under 150-word curiosity-driven email body.")

class CampaignDrafts(BaseModel):
    """Structured AI-generated marketing content."""
    blog_title: str = Field(..., description="A concise, punchy title for the blog post (max 10 words).")
    blog: str = Field(..., description="Full-length PAS-structured markdown blog post (the body only).")
    linkedin_thread: Optional[List[str]] = Field(default_factory=list, description="Optional array of 3-5 social media posts.")
    instagram_post: Optional[str] = Field(None, description="Optional high-engagement Instagram caption with hashtags.")
    email: Optional[EmailDraft] = Field(None, description="Optional B2B outreach email draft.")
